services:
  springboot-app:
    container_name: simple-assembly-lang
    image: sim-asm-lang
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: program
      MYSQL_ROOT_PASSWORD: root

